import express from 'express';
import { getCategories, getAllCategories, getCategory, createCategory, updateCategory, deleteCategory } from '../controllers/categoryController.js';
import { protect, admin } from '../middleware/auth.js';
const router = express.Router();
router.get('/', getCategories);
router.get('/all', getAllCategories);
router.get('/:slug', getCategory);
router.post('/', protect, admin, createCategory);
router.put('/:id', protect, admin, updateCategory);
router.delete('/:id', protect, admin, deleteCategory);
export default router;
