import express from 'express';
import { getProducts, getProduct, getFeaturedProducts, getTopProducts, getRelatedProducts, getDeals, createProduct, updateProduct, deleteProduct, getAdminProducts } from '../controllers/productController.js';
import { createReview, getProductReviews } from '../controllers/reviewController.js';
import { protect, admin } from '../middleware/auth.js';
import { reviewValidator } from '../middleware/validator.js';
const router = express.Router();
router.get('/', getProducts);
router.get('/featured/list', getFeaturedProducts);
router.get('/top/rated', getTopProducts);
router.get('/deals/list', getDeals);
router.get('/admin/all', protect, admin, getAdminProducts);
router.get('/:slug', getProduct);
router.get('/:id/related', getRelatedProducts);
router.post('/:productId/reviews', protect, reviewValidator, createReview);
router.get('/:productId/reviews', getProductReviews);
router.post('/', protect, admin, createProduct);
router.put('/:id', protect, admin, updateProduct);
router.delete('/:id', protect, admin, deleteProduct);
export default router;
