import express from 'express';
import { getUserProfile, updateUserProfile, addAddress, deleteAddress, toggleWishlist, getUsers, deleteUser, updateUser } from '../controllers/userController.js';
import { protect, admin } from '../middleware/auth.js';
const router = express.Router();
router.get('/profile', protect, getUserProfile);
router.put('/profile', protect, updateUserProfile);
router.post('/addresses', protect, addAddress);
router.delete('/addresses/:addressId', protect, deleteAddress);
router.post('/wishlist', protect, toggleWishlist);
router.get('/', protect, admin, getUsers);
router.delete('/:id', protect, admin, deleteUser);
router.put('/:id', protect, admin, updateUser);
export default router;
